### ISSUE TITLE
Expected 2 got 1

### ISSUE THREAD

**Issue by ansi82** [shashankbafna/cowin-vaccination-book-slot#3]
![Screenshot (47)](https://user-images.githubusercontent.com/84778690/120327213-22be0d00-c307-11eb-9d96-30d739b7bbf1.png)

**Comment by ansi82** [comment]
I have already upgraded my requests still this error is coming

**Comment by shashankbafna** [comment]
Looks like the bot token provided was not properly as instructed.
As per the instruction, bot token msg received from botfather should be forwarded.

Anyways, This is a good catch, I have updated the code.
