### ISSUE TITLE
Errror

### ISSUE THREAD

**Issue by arunjyoti-ec** [shashankbafna/cowin-vaccination-book-slot#5]
D:\Cowin\cowin-vaccination-book-slot-main\src>python ./cowinVaccinationSlotAutoBooking.py
Traceback (most recent call last):
  File "D:\Cowin\cowin-vaccination-book-slot-main\src\cowinVaccinationSlotAutoBooking.py", line 6, in <module>
    from utils import generate_token_OTP, check_and_book, beep, BENEFICIARIES_URL, WARNING_BEEP_DURATION, \
  File "D:\Cowin\cowin-vaccination-book-slot-main\src\utils.py", line 205
    """Search by Pincode? Or by State/District? \nEnter 1 for Pincode or 2 for State/District. (Default 2) : """)
                                                                                                                ^
SyntaxError: unmatched ')

**Comment by shashankbafna** [comment]
Fixed. Thank you for your valuable input.
Do not forget to star mark the project in Github, if it is helpful.
