### ISSUE TITLE
how to use it on windows 10

### ISSUE THREAD

**Issue by saihivarkar** [shashankbafna/cowin-vaccination-book-slot#7]
I read your #readme for installing it on windows. I am unable to install the dependencies. I am a novice, so I would require your help. I am learning this so that I can help underprivileged people.

**Comment by shashankbafna** [comment]
Please share the details what is it failing with, please share screenshots.

If it is just pip then.

1) Check if python is installed or not?
Python now, always comes with pip.
 - If it is installed, then env variables are not set.
    - For setting env variables, follow this link: https://www.journaldev.com/30076/install-python-windows-10
 - If it is not installed, please go ahead & install it & make sure to check add the python to Env path.

**Comment by saihivarkar** [comment]
thank you for the information.  i will give it try and let u know whether it went through smoothly!
